title: Swift-Lang-Learn
email: abid@tyrann.net
description: >- # this means to ignore newlines until "baseurl:"
  Thrills & spills on the Swift learning journey.
baseurl: ""
url: "https://swift-lang-learn.github.io"
permalink: pretty
logo: "/assets/img/logo.svg"
phone: +1
location: "United States"

header_pages:
  - index.html
  - about.md
  - portfolio.md

words_per_minute: 200

# Default post thumbnail path
posthumbnail: images/any.jpg

show_excerpts: true

# Amount of post to show on home page
paginate: 5

disqus:
  shortname: ""

mailchimp-list: //redgadgets.us10.list-manage.com/subscribe/post?u=210acce5db69d3d4a04b0e25d&amp;id=08c6708f40"

facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234

google_analytics: UA-134082319-1

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

social:
  name: Abid Khwaja
  links:
    - https://twitter.com/abidDidLoad
    - https://www.facebook.com/abu.iman
    - https://www.linkedin.com/in/abidkhwaja
    - https://github.com/Swift-Lang-Learn

google_analytics: UA-134082319-1

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

author: Abid Khwaja

twitter:
  username: abidDidLoad
  card: summary

twitter_username: abidDidLoad
github_username:  Swift-Lang-Learn
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username:
pinterest_username:
youtube_username:

rss: true


# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
